import pygame

FPS = 60

WINDOW_WIDTH = 1300
WINDOW_HEIGHT = 800
DISPLAY_WIDTH = 1000
DISPLAY_HEIGHT = 600

PLAYER_WIDTH = 42
PLAYER_HEIGHT = 48

LIGHT_ENEMY_WIDTH = 42
LIGHT_ENEMY_HEIGHT = 48

HEAVY_ENEMY_WIDTH = 56
HEAVY_ENEMY_HEIGHT = 64

FLIGHT_ENEMY_WIDTH = 54
FLIGHT_ENEMY_HEIGHT = 60

SOAR_ENEMY_WIDTH = 52
SOAR_ENEMY_HEIGHT = 58

SHOOTING_ENEMY_WIDTH = 42
SHOOTING_ENEMY_HEIGHT = 48

TILE_SIZE = 32

FRICTION = 35
GRAVITY = 2400
FLOOR = 624

BULLET_SIZE = 12
SHOOTING_COOLDOWN = 300

window = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))
display = pygame.Surface((DISPLAY_WIDTH, DISPLAY_HEIGHT))
clock = pygame.time.Clock()