import pygame

FPS = 90

WINDOW_WIDTH = 1300
WINDOW_HEIGHT = 800
DISPLAY_WIDTH = 1000
DISPLAY_HEIGHT = 600

PLAYER_WIDTH = 42
PLAYER_HEIGHT = 48

LIGHT_ENEMY_WIDTH = 42
LIGHT_ENEMY_HEIGHT = 48

HEAVY_ENEMY_WIDTH = 56
HEAVY_ENEMY_HEIGHT = 64

FLIGHT_ENEMY_WIDTH = 54
FLIGHT_ENEMY_HEIGHT = 60

SOAR_ENEMY_WIDTH = 52
SOAR_ENEMY_HEIGHT = 58

SHOOTING_ENEMY_WIDTH = 42
SHOOTING_ENEMY_HEIGHT = 48

BURST_ENEMY_WIDTH = 56
BURST_ENEMY_HEIGHT = 48

SPECTER_ENEMY_WIDTH = 42
SPECTER_ENEMY_HEIGHT = 48

TILE_SIZE = 32

FRICTION = 35
GRAVITY = 2400
FLOOR = 624

BULLET_SIZE = 12

NEGATOR_SIZE = 35

HEART_IMAGE_WIDTH = 40
HEART_IMAGE_HEIGHT = 40

EMPTY_HEART_IMAGE_WIDTH = 40
EMPTY_HEART_IMAGE_HEIGHT = 40

SHIELD_IMAGE_WIDTH = 40
SHIELD_IMAGE_HEIGHT = 48

window = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT), pygame.FULLSCREEN | pygame.SCALED)
pygame.display.set_caption("PyBlast")
display = pygame.Surface((DISPLAY_WIDTH, DISPLAY_HEIGHT))
clock = pygame.time.Clock()